#!/usr/bin/lua

local site = require 'gluon.site'
local uci = require("simple-uci").cursor()

-- Clean up previous configuration
uci:delete_all('wireguard', 'wireguard', function(peer)
	return peer.preserve ~= '1'
end)

local mesh_enabled = uci:get_bool('gluon', 'mesh_vpn', 'enabled') -- default
	or uci:get_bool('fastd', 'mesh_vpn', 'enabled') --migration
	or wg_enabled -- specific config

uci:section("wireguard", "wireguard", "mesh_vpn", {
	broker = site.mesh_vpn.wireguard.broker(),
})

uci:save('wireguard')
uci:save('gluon')
