#!/usr/bin/lua

local site = require 'gluon.site'
local uci = require("simple-uci").cursor()

-- Clean up previous configuration
uci:delete_all('wireguard', 'wireguard', function(peer)
	return peer.preserve ~= '1'
end)

uci:section("wireguard", "wireguard", "mesh_vpn", {
	broker = site.mesh_vpn.wireguard.broker()
})

uci:save('wireguard')
uci:save('gluon')
