#!/bin/sh

rm /etc/config/wireguard
touch /etc/config/wireguard

#Ist multidomainsupport aktiviert?
domain=$(uci get gluon.core.domain)

if [ -n "$domain" ] && [ -f /lib/gluon/domains/$domain.json ]; then {
        datei="/lib/gluon/domains/$domain.json";
} else {                                        #falls ja
        datei="/lib/gluon/site.json";
}
fi

uci set wireguard.mesh_vpn=wireguard
uci set wireguard.mesh_vpn.broker=$(jsonfilter -i $datei -e "$.mesh_vpn.wireguard.broker")
uci commit wireguard
